project/home/forms.py
__author__ = 'workhorse'

from flask_wtf import Form
from wtforms import StringField, FileField, DateTimeField, IntegerField, BooleanField, FloatField
from wtforms.validators import DataRequired, Length

class MessageForm(Form):
    title = StringField("Title", validators=[DataRequired()])
    description = StringField(
        "Description", validators=[DataRequired(), Length(max=140)]
    )
    image = FileField("Product Image")

class CourseForm(Form):
    course_name = StringField("Title", validators=[DataRequired()])
    course_description = StringField("Course Description", validators=[DataRequired()])
    course_location = StringField("Course Location", validators=[DataRequired()])
    start_date = DateTimeField("Start Date", validators=[DataRequired()])
    end_date = DateTimeField("End Date", validators=[DataRequired()])
    start_time = DateTimeField("Start Time", validators=[DataRequired()])
    end_time = DateTimeField("End Time", validators=[DataRequired()])
    max_number_students = IntegerField("Max Students", validators=[DataRequired()])
    spaces_left = IntegerField("Spaces Left")
    is_active = BooleanField("Is Active")
    price = FloatField("Price in Dollars")
    age_range = StringField("Age range", validators=[DataRequired()])
    image_path = FileField("Product Image")

project/users/forms.py
__author__ = 'workhorse'
from flask_wtf import Form
from wtforms import StringField, PasswordField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo

class LoginForm(Form):
    username = StringField("Username", validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired()])


class RegisterForm(Form):
    username = StringField(
        "username",
        validators=[DataRequired(), Length(min=3, max=25)]
    )
    email = StringField(
        "email",
        validators=[DataRequired(), Email(message = None),Length(min=3, max=40)]
    )
    password= PasswordField(
        "password",
        validators=[DataRequired(), Length(min=6, max=25)]
    )
    confirm= PasswordField(
        "Repeat password",
        validators=[DataRequired(), EqualTo('password', message = "Passwords must match")]
    )

class AdminUserCreateForm(Form):
    username =  StringField('Username', [DataRequired()])
    password = PasswordField('Password', [DataRequired()])
    email = StringField("Email   ",validators=[DataRequired(), Email(message = None),Length(min=3, max=40)]
    )
    admin = BooleanField('Is Admin ?')

class AdminUserUpdateForm(Form):
    username =  StringField('Username', [DataRequired()])
    admin = BooleanField('Is Admin ?')

project/home/views.py
################################################
# import the Flask class from the flask module #
################################################
from functools import wraps # pragma: no cover
from flask import Blueprint, render_template,request, flash,redirect, url_for, current_app # pragma: no cover
from flask.ext.login import login_required, current_user # pragma: no cover
from forms import CourseForm # pragma: no cover
from project import db # pragma: no cover
from project.models import Course # pragma: no cover
from project.decorators import check_confirmed
import os
from werkzeug import secure_filename
from boto.s3.connection import S3Connection
import stripe
import uuid
import sys


##########################
#### Config ##############
##########################

home_blueprint = Blueprint('home', __name__,
                            template_folder='templates') # pragma: no cover





stripe_keys = {
    'secret_key': 'sk_test_66JgwFeJaEa0NNrxgBjv9Scr',
    'publishable_key': 'pk_test_dzYx1fZrr100wb02ctTHbYUz'
}

stripe.api_key = stripe_keys['secret_key']

###########################
# login required decorator#
###########################
#not needed if using flask-login
#def login_required(f):
#    @wraps(f)
#    def wrap(*args, **kwargs):
#       if 'logged_in' in session:
#            return f(*args, **kwargs)
#        else:
#            flash('You need to login first.')
#            return redirect(url_for('users.login'))
#    return wrap

def allowed_file(filename):
    return '.' in filename and filename.lower().rsplit('.', 1)[1] in current_app.config['ALLOWED_EXTENSIONS']

# use decorators to link the function to a url

@home_blueprint.context_processor
def utility_processor():
    def format_price(amount):
        return u'{0:.0f}'.format(100*int(amount))
    return dict(format_price=format_price)

@home_blueprint.context_processor
def utility_processor():
    def format_price(amount):
        return u'{0:.0f}'.format(100*int(amount))
    return dict(format_price=format_price)

@home_blueprint.context_processor
def utility_processor():
    def format_price_dollars(amount):
        return u'${0:.2f}'.format(int(amount))
    return dict(format_price_dollars=format_price_dollars)

@home_blueprint.route('/', methods = ["GET", "POST"])
@home_blueprint.route('/index', methods = ["GET", "POST"])
def home():
    # return "Hello, World!"  # return a string
    #posts = BlogPost.query.filter(BlogPost.user_id==current_user.id).all()
    #posts = db.session.query(BlogPost).all()

    courses = Course.query.all()
    return render_template('base.html', courses=courses, key=stripe_keys['publishable_key'] )  # render a templates , form=form, posts=posts

@home_blueprint.route('/welcome')
def welcome():
    return render_template('welcome.html')  # render a templates



@home_blueprint.route('/create', methods = ["GET", "POST"])

def create():
    # return "Hello, World!"  # return a string
    error = None
    form = CourseForm(request.form)
    if form.validate_on_submit():
        image = request.files['image']
        filename = ''
        if image and allowed_file(image.filename):
            filename = image.filename
            conn = S3Connection(
            aws_access_key_id=current_app.config['AWS_ACCESS_KEY'],
            aws_secret_access_key = current_app.config['AWS_SECRET_KEY']
            )
            bucket = conn.create_bucket(current_app.config['AWS_BUCKET'])
            key = bucket.new_key(filename)
            key.set_contents_from_file(image)
            key.make_public()
            key.set_metadata(
            'Content-Type', 'image/' + filename.split('.')[-1].lower()
            )
        new_course = Course(form.course_name.data,
                            form.course_description.data,
                            form.course_location.data,
                            form.start_date.data,
                            form.end_date.data,
                            form.start_time.data,
                            form.end_time.data,
                            form.max_number_students.data,
                            form.spaces_left.data,
                            form.is_active.data,
                            form.price.data,
                            form.age_range.data,
                            filename,
                            current_user.id)
        db.session.add(new_course)
        db.session.commit()
        flash("New course was successfully posted.  Thanks.")
        return redirect(url_for('home.home'))
    else:
        #posts = BlogPost.query.filter(BlogPost.user_id==current_user.id).all()
        #posts = db.session.query(BlogPost).all()

        return render_template('create.html', form=form )  # render a templates , form=form, posts=posts

project/users/views.py
###########################
#### imports ##############
###########################

from flask import flash, redirect, render_template, request,\
     url_for, Blueprint, abort # pragma: no cover
from flask.ext.login import login_user,login_required, logout_user, current_user # pragma: no cover
from functools import wraps #- not needed with flask login
from forms import LoginForm, RegisterForm, PasswordField, AdminUserCreateForm, AdminUserUpdateForm # pragma: no cover
from project.models import User, BlogPost, Purchase, Course, bcrypt  # pragma: no cover
from project import db # pragma: no cover
from project.token import generate_confirmation_token, confirm_token #pragma: no cover
from project.email import send_email
import datetime #pragma: no cover
from flask.ext.admin import BaseView, expose, Admin
from flask.ext.admin.contrib.sqla import ModelView
from functools import wraps
import stripe
import uuid
import sys



##########################
#### Config ##############
##########################

users_blueprint = Blueprint('users', __name__,
                            template_folder='templates') # pragma: no cover




################################
# login required decorator######
# not needed with flask login###
################################
def admin_login_required(func):
    @wraps(func)
    def decorated_view(*args, **kwargs):
        if not current_user.is_admin():
            return abort(403)
        return func(*args, **kwargs)
    return decorated_view
#def login_required(test):
#    @wraps(test)
#    def wrap(*args, **kwargs):
#        if 'logged_in' in session:
#            return test(*args, **kwargs)
#        else:
#            flash('You need to login first.')
#            return redirect(url_for('.login'))
#    return wrap


@users_blueprint.route('/aboutus')
def about_us():
    return render_template('about_us.html')

# route for handling the login page logic
@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    error = None
    form = LoginForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            user =User.query.filter_by(name=request.form['username']).first()
            if user is not None and bcrypt.check_password_hash(user.password, request.form['password']):
                #session['logged_in'] = True #Not need if using flasklogin's decorators
                login_user(user)
                flash('You were logged in.')
                return redirect(url_for('home.home'))
            else:
                error = 'Invalid Credentials. Please try again.'
    return render_template('login.html', form=form, error=error)


@users_blueprint.route('/logout')
@login_required
def logout():
    #session.pop('logged_in', None) - only needed if managing sessions
    logout_user()
    flash('You were logged out.')
    return redirect(url_for('home.welcome'))



@users_blueprint.route('/confirm/<token>')
@login_required
def confirm_email(token):
    try:
        email = confirm_token(token)
    except:
        flash("The confirmation link is invalid or has expired.", "danger")
        return redirect(url_for('users.login'))
    user = User.query.filter_by(email=email).first_or_404()
    if user.confirmed:
        flash('Account already confirmed. Please login.', 'success')
    else:
        user.confirmed = True
        user.confirmed_on = datetime.datetime.now()
        db.session.add(user)
        db.session.commit()
        flash('You have confirmed your account. Thanks!', 'success')
    return redirect(url_for('home.home'))

@users_blueprint.route('/user-register', methods=["GET", "POST"])
def register():
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        user = User(
            username = form.username.data,
            email = form.email.data,
            password=form.password.data
        )
        db.session.add(user)
        db.session.commit()

        token = generate_confirmation_token(user.email)
        confirm_url = url_for("users.confirm_email", token=token, _external=True)
        html = render_template('activate.html', confirm_url=confirm_url)
        subject = "Please confirm your email"
        send_email(user.email, subject, html)
        login_user(user) #may want to  removed - want to force user to authenticate before logging in


        return redirect(url_for("users.unconfirmed"))
    return render_template('register.html', form=form)


@users_blueprint.route('/unconfirmed')
@login_required
def unconfirmed():
    if current_user.confirmed:
        return redirect('home.home')
    flash('Please confirm your account!', 'warning')
    return render_template('unconfirmed.html')



@users_blueprint.route('/resend')
@login_required
def resend_confirmation():
    token = generate_confirmation_token(current_user.email)
    confirm_url = url_for('users.confirm_email', token=token, _external=True)
    html = render_template("activate.html", confirm_url=confirm_url)
    subject = "Please confirm your email"
    send_email(current_user.email, subject, html)
    flash("A new confirmation email has been sent.","success")
    return redirect(url_for("users.unconfirmed"))


##################
## Admin #########
##################

class MyView(BaseView):
    @expose("/")
    def index(self):
        return self.render("index-admin.html")

    def is_accessible(self):
        return current_user.is_authenticated() and current_user.is_admin()

    def _handle_view(self, name, **kwargs):
        if not self.is_accessible():
            return redirect(url_for('login', next=request.url))

class MyView(ModelView):

    def is_accessible(self):
        return current_user.is_authenticated() and current_user.is_admin()

    def _handle_view(self, name, **kwargs):
        if not self.is_accessible():
            return redirect(url_for('users.login', next=request.url))


    # Disable model creation


    # Override displayed fields
    column_list = ('name', 'email','admin','registered_on')

    def create_model(self, form):
        model = self.model(
        form.name.data, form.email.data, form.password.data,
        form.admin.data
        )
        form.populate_obj(model)
        self.session.add(model)
        self.on_model_change(form, model, True)
        self.session.commit()
        return redirect(url_for('home.home'))

    def __init__(self, session, **kwargs):
        # You can pass name and other parameters if you want to
        super(MyView, self).__init__(User, session, **kwargs)


class PostView(ModelView):
    # Disable model creation

    def is_accessible(self):
        return current_user.is_authenticated() and current_user.is_admin()

    def _handle_view(self, name, **kwargs):
        if not self.is_accessible():
            return redirect(url_for('users.login', next=request.url))


    can_create = False

    # Override displayed fields
    column_list = ('title', 'description')

    def __init__(self, session, **kwargs):
        # You can pass name and other parameters if you want to
        super(PostView, self).__init__(BlogPost, session, **kwargs)

project/users/templates/about_us.html
{% extends "base.html" %}

{% block maincontent %}

here i am

{% endblock %}

project/users/templates/activate.html
<p>Welcome! Thanks for signing up.   Please follow this link to activate your account:</p>
<p><a href="{{ confirm_url }}">{{ confirm_url }}</a></p>
<br>
<p>Cheers!</p>

project/users/templates/admin-home.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <h1>Welcome to the Admin Demo</h1>
<h3>Hey {{ current_user.username }}!!</h3>
  <a href="{{ url_for('users.users_list_admin') }}">List of all users</a>
  <br/>
  <a href="{{ url_for('users.user_create_admin') }}">Create a new user</a>
  <br/>
  <a href="{{ url_for('users.logout') }}">Click here to logout</a>
  </div>
{% endblock %}

project/users/templates/home.html
{% extends 'base.html' %}

{% block content %}
  <h1>Welcome to the Authentication Demo</h1>
  {% if current_user.is_authenticated() %}
    <h3>Hey {{ current_user.username }}!!</h3>
    <a href="{{ url_for('users.logout') }}">Click here to logout</a>
  {% else %}
  Click here to <a href="{{ url_for('users.login') }}">login</a> or <a href="{{ url_for('users.register') }}">register</a>
  {% endif %}
  {% block container %}{% endblock %}
{% endblock %}

project/users/templates/index.html
{% extends "base.html" %}

project/users/templates/login.html
{% block content %}

      <h1>Please Login</h1>
      <br>
      <form class="form-signin" action = ""  method = "post">
        {{ form.csrf_token }}
        <p>{{ form.username(placeholder="username") }}
        <span class="error">
        {% if form.username.errors %}
            {% for error in form.username.errors %}
                {{ error }}
            {% endfor %}
         {% endif %}
        </span>
       </p>
       <p>
       {{ form.password(placeholder="password") }}
       <span class="error">
        {% if form.password.errors %}
            {% for error in form.password.errors %}
                {{ error }}
            {% endfor %}
         {% endif %}
        </span>
        </p>
      <button class="btn btn-sm btn-success" type="submit">Sign in</button>
     </form>
     {% endblock %}

project/users/templates/posted-stuff.html
<p>Welcome! Thanks for signing up.   Please follow this link to activate your account:</p>
<p><a href="{{ confirm_url }}">{{ confirm_url }}</a></p>
<br>
<p>Cheers!</p>

project/users/templates/register.html
{% extends "base.html" %}
{% block content %}
<h1>Please Register</h1>
<br>
<form class="form-signin" role = 'form' method = "post" action = "">
 {{ form.csrf_token }}
<p>
{{ form.username(placeholder = "username")}}
        <span class="error">
        {% if form.username.errors %}
            {% for error in form.username.errors %}
                {{ error }}
            {% endfor %}
         {% endif %}
        </span>
        </p>
<p>
{{ form.email(placeholder = "email")}}
        <span class="error">
        {% if form.email.errors %}
            {% for error in form.email.errors %}
                {{ error }}
            {% endfor %}
         {% endif %}
        </span>
        </p>

    <p>
    {{ form.password(placeholder = "password")}}
        <span class="error">
        {% if form.password.errors %}
            {% for error in form.password.errors %}
                {{ error }}
            {% endfor %}
         {% endif %}
        </span>
        </p>
   <p>
    {{ form.confirm(placeholder = "confirm password")}}
        <span class="error">
        {% if form.confirm.errors %}
            {% for error in form.confirm.errors %}
                {{ error }}
            {% endfor %}
         {% endif %}
        </span>
        </p>


<button class="bt btn-sm btn-success" type="submit">Register !</button>
</form>

{% endblock %}

project/users/templates/some-template.html
This is a template just for demonstration of Flask Admin Views.

project/users/templates/unconfirmed.html
{% extends "base.html" %}

{% block content %}

<h1>Welcome!</h1>
<br>
<p>You have not confirmed your account. Please check your inbox (and your spam folder) - you should have received an email with a confirmation link.</p>
<p>Didn't get the email? <a href="{{ url_for('users.resend_confirmation') }}">Resend</a>.</p>

{% endblock %}

project/users/templates/user-create-admin.html
{% extends 'home.html' %}

{% block container %}
  <div class="top-pad">
    <form method="POST"action="{{ url_for('users.user_create_admin') }}" role="form">
      {{ form.csrf_token }}
      <div class="form-group">{{ form.username.label }}: {{ form.username() }}</div>
      <div class="form-group">{{ form.email.label }}:{{ form.email() }}</div>
      <div class="form-group">{{ form.password.label }}: {{ form.password() }}</div>
      <div class="form-group">{{ form.admin.label }}: {{ form.admin() }}</div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form>
  </div>
{% endblock %}

project/users/templates/user-register.html
{% extends "base.html" %}
{% block content %}
<h1>Please Register</h1>
<br>
<form class="form-signin" role = 'form' method = "post" action = "">
 {{ form.csrf_token }}
<p>
{{ form.username(placeholder = "username")}}
        <span class="error">
        {% if form.username.errors %}
            {% for error in form.username.errors %}
                {{ error }}
            {% endfor %}
         {% endif %}
        </span>
        </p>
<p>
{{ form.email(placeholder = "email")}}
        <span class="error">
        {% if form.email.errors %}
            {% for error in form.email.errors %}
                {{ error }}
            {% endfor %}
         {% endif %}
        </span>
        </p>

    <p>
    {{ form.password(placeholder = "password")}}
        <span class="error">
        {% if form.password.errors %}
            {% for error in form.password.errors %}
                {{ error }}
            {% endfor %}
         {% endif %}
        </span>
        </p>
   <p>
    {{ form.confirm(placeholder = "confirm password")}}
        <span class="error">
        {% if form.confirm.errors %}
            {% for error in form.confirm.errors %}
                {{ error }}
            {% endfor %}
         {% endif %}
        </span>
        </p>


<button class="bt btn-sm btn-success" type="submit">Register !</button>
</form>

{% endblock %}

project/users/templates/user-update-admin.html
{% extends 'home.html' %}

{% block container %}
  <div class="top-pad">
    <form
        method="POST"
        action="{{ url_for('users.user_update_admin', id=user.id) }}"
        role="form">
      {{ form.csrf_token }}
      <div class="form-group">{{ form.username.label }}: {{ form.username() }}</div>
      <div class="form-group">{{ form.admin.label }}: {{ form.admin() }}</div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form>
  </div>
{% endblock %}

project/users/templates/users-list-admin.html
{% extends 'admin-home.html' %}

{% block content %}
  <h3>Hey {{ current_user.name }}!! Below is the list of users in system</h3>
  <br/>
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>ID</th>
        <th>Username</th>
        <th>Is Admin ?</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for user in users %}
        <tr>
          <td>{{ user.id }}</td>
          <td>{{ user.name }}</td>
          <td>{{ user.admin }}</td>
          <td>
            <a href="{{ url_for('users.user_update_admin', id=user.id) }}" class="btn btn-info btn-xs">Edit</a>
          </td>
          <td>
            <form  method = "post" action = "{{ url_for('users.user_delete_admin', id=user.id) }}">
            <button class="btn btn-danger btn-xs" type="submit">Delete</button>
            </form>

          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}