project/buy/forms.py
__author__ = 'workhorse'

from flask_wtf import Form

from wtforms.ext.sqlalchemy.fields import QuerySelectField
from wtforms import StringField,IntegerField
from wtforms.validators import DataRequired, Length, Email
from project.models import Course

def select_group():
        return Course.query.all()


class EnrollmentForm(Form):

    email = StringField(
        "email",
        validators=[DataRequired(), Email(message = None),Length(min=3, max=40)]
    )
    product= IntegerField('Product ID')
    payment_method = StringField('Payment', validators=[DataRequired()])
    notes = StringField('Notes', validators=[DataRequired()])

project/buy/__init__.py
__author__ = 'workhorse'

project/buy/views.py
__author__ = 'workhorse'

from flask import flash, redirect, render_template, request,\
     url_for, Blueprint, current_app, abort # pragma: no cover
from flask.ext.login import login_user,login_required, logout_user, current_user # pragma: no cover
from functools import wraps #- not needed with flask login
from project.models import User, BlogPost, Purchase, Course, bcrypt  # pragma: no cover
from project import db # pragma: no cover
from project.token import generate_confirmation_token, confirm_token #pragma: no cover
from project.email import send_email
import datetime #pragma: no cover
from flask.ext.admin import BaseView, expose, Admin
from flask.ext.admin.contrib.sqla import ModelView
from functools import wraps
from .forms import EnrollmentForm
import stripe
import uuid
import sys




##########################
#### Config ##############
##########################

buy_blueprint = Blueprint('buy', __name__,
                            template_folder='templates') # pragma: no cover


stripe_keys = {
    'secret_key': 'sk_test_66JgwFeJaEa0NNrxgBjv9Scr',
    'publishable_key': 'pk_test_dzYx1fZrr100wb02ctTHbYUz'
}

stripe.api_key = stripe_keys['secret_key']



##############
# ADMIN ######
##############
class CourseView(ModelView):
    # Disable model creation

    def is_accessible(self):
        return current_user.is_authenticated() and current_user.is_admin()

    def _handle_view(self, name, **kwargs):
        if not self.is_accessible():
            return redirect(url_for('users.login', next=request.url))



    # Override displayed fields
    column_list = ("course_name", "age_range","course_description", "course_location", "start_date","end_date",
                 "start_time","end_time","max_number_students","spaces_left","is_active", "price")



    def __init__(self, session, **kwargs):
        # You can pass name and other parameters if you want to
        super(CourseView, self).__init__(Course, session, **kwargs)



class PurchaseView(ModelView):
    # Disable model creation

    def is_accessible(self):
        return current_user.is_authenticated() and current_user.is_admin()

    def _handle_view(self, name, **kwargs):
        if not self.is_accessible():
            return redirect(url_for('users.login', next=request.url))



    # Override displayed fields
    column_list = ( "email", "product_id", "product","payment_method","notes","date_purchased")

    def create_model(self, form):
        model = self.model(
        form.email.data,
        form.product.data,
        form.payment_method.data,
        form.notes.data,
        form.date_purchased.data
        )
        form.populate_obj(model)
        self.session.add(model)
        self.on_model_change(form, model, True)
        self.session.commit()
        return redirect(url_for('home.home'))

    def __init__(self, session, **kwargs):
        # You can pass name and other parameters if you want to
        super(PurchaseView, self).__init__(Purchase, session, **kwargs)


@buy_blueprint.route('/courses', methods=["GET", "POST"])
def courses():
    courses = Course.query.all()
    return render_template("purchase.html", courses=courses, key=stripe_keys['publishable_key'])

@buy_blueprint.context_processor
def utility_processor():
    def format_price(amount):
        return u'{0:.0f}'.format(100*int(amount))
    return dict(format_price=format_price)
@buy_blueprint.context_processor

def utility_processor():
    def format_price_dollars(amount):
        return u'${0:.2f}'.format(int(amount))
    return dict(format_price_dollars=format_price_dollars)

"""
@buy_blueprint.route('/register3', methods=["GET", "POST"])
def register3():
    course_id = request.form['product']
    course = Course.query.get(course_id)
    return render_template('register.html', course=course)
"""


@buy_blueprint.route('/register/', methods=["GET", "POST"])
def register():
    stripe.api_key = "sk_test_66JgwFeJaEa0NNrxgBjv9Scr"
    error = None
    form = EnrollmentForm(request.form)
    courses = Course.query.all()
    if request.method == 'POST':
        if form.validate_on_submit():
            token = request.form['stripeToken']
            course_id = request.form['product']
            course = Course.query.get(course_id)
            purchase = Purchase(uuid=str(uuid.uuid4()),
            email=form.email.data,
            product=form.product.data,
            payment_method = form.payment_method.data,
            notes = form.notes.data)
            charge = stripe.Charge.create(
                amount=int(int(course.price) * 100),
                currency='cad',
                card=token,
                description=form.email.data)
            db.session.add(purchase)
            db.session.commit()
            return redirect(url_for('home.home'))
        else:
            return render_template('register.html',form=form, error=error)

    else:
        return render_template('register.html',form=form, error=error)




@buy_blueprint.route('/buy', methods=['POST'])
def buy():
    stripe_token = request.form['stripeToken']
    email = request.form['stripeEmail']
    course_id = request.form['course_id']
    course = Course.query.get(course_id)
    try:
        charge = stripe.Charge.create(
                amount=int(int(course.price) * 100),
                currency='cad',
                card=stripe_token,
                description=email)
    except stripe.CardError, e:
        return """<html><body><h1>Card Declined</h1><p>Your chard could not
        be charged. Please check the number and/or contact your credit card
        company.</p></body></html>"""
    print charge
    purchase = Purchase(uuid=str(uuid.uuid4()),
            email=email,
            product=course)
    course.spaces_left -=1
    db.session.add(purchase)
    db.session.commit()
    subject='Thanks for your purchase!'
    html=""""<html><body><h1>Thanks for registering for {}</h1>
    <p>A member of our team will follow up with you to get the complete details for your child.<p>
    <p>Course Name: {}</h2>
    <p>Course Price: {}</p>
    <p>Course Description: {}</p>
    <p>Course Location: {}</p>
    <p>Start Date: {}</p>
    <p>End Date: {}</p>
    <p>Start Time: {}</p>
    <p>End Time: {}</p>""".format(course.course_name, course.course_name,
        "${:,.2f}".format(course.price),
        course.course_description,
        course.course_location,
        course.start_date.strftime('%b %d, %Y'),
        course.start_date.strftime('%b %d, %Y'),
        course.start_time.strftime('%I:%M %p'),
        course.end_time.strftime('%I:%M %p')
    )
    send_email(email, subject, html)
    return redirect(url_for('home.home'))


@buy_blueprint.route('/test')
def test():
    return """
<http><body><form action="buy" method="POST">
<script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="pk_test_w3qNBkDR8A4jkKejBmsMdH34"
    data-amount="999"
    data-name="jeffknupp.com"
    data-description="Writing Idiomatic Python 3 PDF ($9.99)">
</script>
<input type="hidden" name="product_id" value="2" />
</form>
</body>
</html>
"""

if __name__ == '__main__':
    sys.exit(current_app.run(debug=True))

project/buy/templates/products.html
{% extends 'base.html' %}
{% block container %}
<div class="top-pad">
<h3>Hola Friend! Looks like in your quest you have reached a
location which does not exist yet.</h3>
<h4>To continue, either check your map location (URL) or go
back <a href="{{ url_for('home.index') }}">home</a></h4>
</div>
{% endblock %}

project/buy/templates/purchase.html
{% extends "base.html" %}

{% block content %}
{% for course in courses %}
<div class="container marketing">
<hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">Course Name: {{ course.course_name }}</h2>

          <p>Max Number of Students: {{ course.max_number_students}}</p>
          <p>Spaces Left:  {{ course.spaces_left }}</p>
          <p>Target Age Group: {{ course.age_range }} years old. </p>
          <p>Remaining Space: {{ course.spaces_left }}</p>
          <p>Course Description: {{ course.course_description }}</p>
          <p>Course Location: {{ course.course_location }}</p>
          <p>Start Date: {{ course.start_date.strftime('%b %d, %Y') }}</p>
          <p>End Date: {{ course.end_date.strftime('%b %d, %Y') }}</p>
          <p>Start Time: {{ course.start_time.strftime('%I:%M %p') }}</p>
          <p>End Time: {{ course.end_time.strftime('%I:%M %p') }}</p>
          <p >Course Price: {{format_price_dollars(course.price)}}</p>

          {% if course.spaces_left > 0 %}
            <form action="{{ url_for('buy.buy')}}" method="POST">
             <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
              data-key={{key}}
              data-amount= {{format_price(course.price)}}
              data-name="Location: {{ course.course_location }}"
              data-label= "Register for: {{course.course_name}}"
              data-description="Start Date: {{course.start_date.strftime('%b %d, %Y')}}">
             </script>
             {% else %}
             <button class="btn btn-primary"> No More Space</button>
             {% endif %}
            <input type="hidden" name="course_id" value="{{course.id}}" />
            </form>
          </div>
        <div class="col-md-5">
          <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto"
          src ="../static/images/kids-computer.jpg"
          alt="Generic placeholder image">
        </div>
      </div>

</div>

{% endfor %}

{% endblock %}

project/buy/templates/register-original.html
{% block content %}


<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<script type="text/javascript">
  // This identifies your website in the createToken call below
  Stripe.setPublishableKey('pk_test_dzYx1fZrr100wb02ctTHbYUz');
  // ...
</script>
<script type="text/javascript">
jQuery(function($) {
  $('#payment-form').submit(function(event) {
    var $form = $(this);

    // Disable the submit button to prevent repeated clicks
    $form.find('button').prop('disabled', true);

    Stripe.card.createToken($form, stripeResponseHandler);

    // Prevent the form from submitting with the default action
    return false;
  });
});

function stripeResponseHandler(status, response) {
  var $form = $('#payment-form');

  if (response.error) {
    // Show the errors on the form
    $form.find('.payment-errors').text(response.error.message);
    $form.find('button').prop('disabled', false);
  } else {
    // response contains id and card, which contains additional card details
    var token = response.id;
    // Insert the token into the form so it gets submitted to the server
    $form.append($('<input type="hidden" name="stripeToken" />').val(token));
    // and submit
    $form.get(0).submit();
  }
};
</script>

      <h1>register</h1>
      <br>
      <form id="payment-form" action = "{{ url_for('buy.register')}}"  method = "post">
        {{ form.csrf_token }}
        <div>{{ form.email.label }}: {{ form.email() }}</div>
        <div>{{ form.product.label }}: {{ form.product() }}</div>
        <div>{{ form.payment_method.label }}: {{ form.payment_method() }}</div>
        <div>{{ form.notes.label }}: {{ form.notes() }}</div>
        <span class="payment-errors"></span>
        <div class="form-row">
        <label>
         <span>Card Number</span>
         <input type="text" size="20" data-stripe="number"/>
        </label>
      </div>

      <div class="form-row">
        <label>
          <span>CVC</span>
          <input type="text" size="4" data-stripe="cvc"/>
        </label>
      </div>

      <div class="form-row">
        <label>
          <span>Expiration (MM/YYYY)</span>
          <input type="text" size="2" data-stripe="exp-month"/>
        </label>
        <span> / </span>
        <input type="text" size="4" data-stripe="exp-year"/>
      </div>


      <button class="btn btn-sm btn-success" type="submit">Submit</button>
     </form>


     {% endblock %}

project/buy/templates/register.html
{%  extends "base.html" %}
  <title>{% block title %}Register your kids{% endblock %}</title>

 {% block scriptstop %}
 {{ super() }}
  <!-- The required Stripe lib -->
  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  <!-- jQuery is used only for this example; it isn't required to use Stripe -->
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
 
  <script type="text/javascript">
    // This identifies your website in the createToken call below
    Stripe.setPublishableKey('pk_test_dzYx1fZrr100wb02ctTHbYUz');

    var stripeResponseHandler = function(status, response) {
      var $form = $('#payment-form');

      if (response.error) {
        // Show the errors on the form
        $form.find('.payment-errors').text(response.error.message);
        $form.find('button').prop('disabled', false);
      } else {
        // token contains id, last4, and card type
        var token = response.id;
        // Insert the token into the form so it gets submitted to the server
        $form.append($('<input type="hidden" name="stripeToken" />').val(token));
        // and re-submit
        $form.get(0).submit();
      }
    };

    jQuery(function($) {
      $('#payment-form').submit(function(e) {
        var $form = $(this);

        // Disable the submit button to prevent repeated clicks
        $form.find('button').prop('disabled', true);

        Stripe.card.createToken($form, stripeResponseHandler);

        // Prevent the form from submitting with the default action
        return false;
      });
    });
  </script>
  {% endblock %}
</head>
<body>
{% block body %}
<div class="container">
<div class="container marketing">
  <h1>Charge $10 with Stripe</h1>
 
  <form action="{{ url_for('buy.register')}}" method="POST" id="payment-form">
    <span class="payment-errors"></span>
    {{ form.csrf_token }}
        <div>{{ form.email.label }}: {{ form.email() }}</div>
        <div>{{ form.product.label }}: {{ form.product() }}</div>
        <div>{{ form.payment_method.label }}: {{ form.payment_method() }}</div>
        <div>{{ form.notes.label }}: {{ form.notes() }}</div>
    <div class="form-row">
      <label>
        <span>Card Number</span>
        <input type="text" size="20" data-stripe="number"/>
      </label>
    </div>
 
    <div class="form-row">
      <label>
        <span>CVC</span>
        <input type="text" size="4" data-stripe="cvc"/>
      </label>
    </div>
 
    <div class="form-row">
      <label>
        <span>Expiration (MM/YYYY)</span>
        <input type="text" size="2" data-stripe="exp-month"/>
      </label>
      <span> / </span>
      <input type="text" size="4" data-stripe="exp-year"/>
    </div>

    <button type="submit">Submit Payment</button>
  </form>
  {% endblock %}
 </div>
 </div>
</body>
</html>